
PERMISSION_READ = "read_document";
PERMISSION_ADD = "add_document";
PERMISSION_CHANGE = "change_document"
PERMISSION_DELETE = "delete_document";

RULE_PERMISSION_DEPENDENCY = (
    PERMISSION_READ,
    PERMISSION_CHANGE,
    PERMISSION_DELETE
)
