PERMISSION_BUNDLE = {
    'classify_bundle':(
        'add_category',
        'change_category',
        'delete_category',
        'add_tag',
        'change_tag',
        'delete_tag',
    ),
    'manageacc_bundle':(
        'add_permission',
        'change_permission',
        'delete_permission',
        'add_group',
        'change_group',
        'delete_group',
        'add_user',
        'change_user',
        'delete_user',    
    )                              
}